var express = require('express');
var path = require('path');
//var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var fs = require('fs');

var routes = require('./routes/index');

/* JS routes for middleware species pages (step 1) */
var ABBREVIATA_BANCROFTI = require('./routes/ABBREVIATA_BANCROFTI');
var ABBREVIATA_HASTASPICULA = require('./routes/ABBREVIATA_HASTASPICULA');
var AGLENCHUS_AGRICOLA = require('./routes/AGLENCHUS_AGRICOLA');
var ALAIMUS_PRIMITIVUS = require('./routes/ALAIMUS_PRIMITIVUS');
var ALLOCORRIGIA_FILIFORMIS = require('./routes/ALLOCORRIGIA_FILIFORMIS');
var ALLOGLOSSIDIUM_CORTI = require('./routes/ALLOGLOSSIDIUM_CORTI');
var AMALARAEUS_PENICILLIGER = require('./routes/AMALARAEUS_PENICILLIGER');
var AMBLYOMMA_AMERICANUM = require('./routes/AMBLYOMMA_AMERICANUM');
var AMBLYOMMA_ASTRION = require('./routes/AMBLYOMMA_ASTRION');
var AMBLYOMMA_CAJENNENSE = require('./routes/AMBLYOMMA_CAJENNENSE');
var AMBLYOMMA_COHAERENS = require('./routes/AMBLYOMMA_COHAERENS');
var AMBLYOMMA_COMPRESSUM = require('./routes/AMBLYOMMA_COMPRESSUM');
var AMBLYOMMA_CUNEATUM = require('./routes/AMBLYOMMA_CUNEATUM');
var AMBLYOMMA_EBERNEUM = require('./routes/AMBLYOMMA_EBERNEUM');
var AMBLYOMMA_EXORNATUM = require('./routes/AMBLYOMMA_EXORNATUM');
var AMBLYOMMA_FALSOMARMOREUM = require('./routes/AMBLYOMMA_FALSOMARMOREUM');
var AMBLYOMMA_FIMBRIATUM = require('./routes/AMBLYOMMA_FIMBRIATUM');
var AMBLYOMMA_FLAVOMACULATUM = require('./routes/AMBLYOMMA_FLAVOMACULATUM');
var AMBLYOMMA_GEMMA = require('./routes/AMBLYOMMA_GEMMA');
var AMBLYOMMA_GEOEMYDAE = require('./routes/AMBLYOMMA_GEOEMYDAE');
var AMBLYOMMA_HEBRAEUM = require('./routes/AMBLYOMMA_HEBRAEUM');
var AMBLYOMMA_HELVOLUM = require('./routes/AMBLYOMMA_HELVOLUM');
var AMBLYOMMA_JAVANENSE = require('./routes/AMBLYOMMA_JAVANENSE');
var AMBLYOMMA_LATUM = require('./routes/AMBLYOMMA_LATUM');
var AMBLYOMMA_LEPIDUM = require('./routes/AMBLYOMMA_LEPIDUM');
var AMBLYOMMA_LIMBATUM = require('./routes/AMBLYOMMA_LIMBATUM');
var AMBLYOMMA_MACULATUM = require('./routes/AMBLYOMMA_MACULATUM');
var AMBLYOMMA_MARMOREUM = require('./routes/AMBLYOMMA_MARMOREUM');
var AMBLYOMMA_NUTTALLI = require('./routes/AMBLYOMMA_NUTTALLI');
var AMBLYOMMA_PAULOPUNCTATUM = require('./routes/AMBLYOMMA_PAULOPUNCTATUM');
var AMBLYOMMA_POMPOSUM = require('./routes/AMBLYOMMA_POMPOSUM');
var AMBLYOMMA_RHINOCEROTIS = require('./routes/AMBLYOMMA_RHINOCEROTIS');
var AMBLYOMMA_SPARSUM = require('./routes/AMBLYOMMA_SPARSUM');
var AMBLYOMMA_SPLENDIDUM = require('./routes/AMBLYOMMA_SPLENDIDUM');
var AMBLYOMMA_TESTUDINARIUM = require('./routes/AMBLYOMMA_TESTUDINARIUM');
var AMBLYOMMA_THOLLONI = require('./routes/AMBLYOMMA_THOLLONI');
var AMBLYOMMA_TRIGUTTATUM = require('./routes/AMBLYOMMA_TRIGUTTATUM');
var AMBLYOMMA_VARIEGATUM = require('./routes/AMBLYOMMA_VARIEGATUM');
var ANAPLECTUS_GRANULOSUS = require('./routes/ANAPLECTUS_GRANULOSUS');
var ANCYLOSTOMA_CANINUM = require('./routes/ANCYLOSTOMA_CANINUM');
var ANGIOSTRONGYLUS_CANTONENSIS = require('./routes/ANGIOSTRONGYLUS_CANTONENSIS');
var ANOMIOPSYLLUS_NUDATUS = require('./routes/ANOMIOPSYLLUS_NUDATUS');
var ANOPLOCEPHALA_PERFOLIATA = require('./routes/ANOPLOCEPHALA_PERFOLIATA');
var APHELENCHUS_AVENAE = require('./routes/APHELENCHUS_AVENAE');
var APHELENCHUS_PARIETINUS = require('./routes/APHELENCHUS_PARIETINUS');
var APLECTANA_ITZOCANENSIS = require('./routes/APLECTANA_ITZOCANENSIS');
var APORCELAIMELLUS_OBTUSICAUDATUS = require('./routes/APORCELAIMELLUS_OBTUSICAUDATUS');
var ARALICHUS_NOBILIS = require('./routes/ARALICHUS_NOBILIS');
var ARCHAEOPSYLLA_ERINACEI = require('./routes/ARCHAEOPSYLLA_ERINACEI');
var ARGAS_BRUMPTI = require('./routes/ARGAS_BRUMPTI');
var ARGAS_CONFUSUS = require('./routes/ARGAS_CONFUSUS');
var ARGAS_PERSICUS = require('./routes/ARGAS_PERSICUS');
var ARGAS_VESPERTILIONIS = require('./routes/ARGAS_VESPERTILIONIS');
var ARGAS_WALKERAE = require('./routes/ARGAS_WALKERAE');
var ARHYTHMORHYNCHUS_BREVIS = require('./routes/ARHYTHMORHYNCHUS_BREVIS');
var ASCARIDIA_BONASAE = require('./routes/ASCARIDIA_BONASAE');
var ASCARIDIA_COLUMBAE = require('./routes/ASCARIDIA_COLUMBAE');
var ASCARIDIA_GALLI = require('./routes/ASCARIDIA_GALLI');
var ASCARIDIA_LINEATA = require('./routes/ASCARIDIA_LINEATA');
var ASCARIS_LUMBRICOIDES = require('./routes/ASCARIS_LUMBRICOIDES');
var ASCARIS_SUUM = require('./routes/ASCARIS_SUUM');
var ASCOCOTYLE_LONGA = require('./routes/ASCOCOTYLE_LONGA');
var ASCOCOTYLE_TENUICOLLIS = require('./routes/ASCOCOTYLE_TENUICOLLIS');
var BAYLISASCARIS_PROCYONIS = require('./routes/BAYLISASCARIS_PROCYONIS');
var BOTHRIOCEPHALUS_CUSPIDATUS = require('./routes/BOTHRIOCEPHALUS_CUSPIDATUS');
var BOTHRIOCROTON_HYDROSAURI = require('./routes/BOTHRIOCROTON_HYDROSAURI');
var BRACHYCOELIUM_SALAMANDRAE = require('./routes/BRACHYCOELIUM_SALAMANDRAE');
var BUNOSTOMUM_PHLEBOTOMUM = require('./routes/BUNOSTOMUM_PHLEBOTOMUM');
var BUNOSTOMUM_TRIGONOCEPHALUM = require('./routes/BUNOSTOMUM_TRIGONOCEPHALUM');
var CAMALLANUS_OXYCEPHALUS = require('./routes/CAMALLANUS_OXYCEPHALUS');
var CAPILLARIA_CONTORTA = require('./routes/CAPILLARIA_CONTORTA');
var CAPILLARIA_TENUISSIMA = require('./routes/CAPILLARIA_TENUISSIMA');
var CARIOS_VESPERTILIONIS = require('./routes/CARIOS_VESPERTILIONIS');
var CENTROCESTUS_FORMOSANUS = require('./routes/CENTROCESTUS_FORMOSANUS');
var CEPHALURIS_COLORADENSIS = require('./routes/CEPHALURIS_COLORADENSIS');
var CERATOPHYLLUS_FARRENI = require('./routes/CERATOPHYLLUS_FARRENI');
var CERATOPHYLLUS_GALLINAE = require('./routes/CERATOPHYLLUS_GALLINAE');
var CERATOPHYLLUS_GAREI = require('./routes/CERATOPHYLLUS_GAREI');
var CERATOPHYLLUS_HIRUNDINIS = require('./routes/CERATOPHYLLUS_HIRUNDINIS');
var CERATOPHYLLUS_STYX = require('./routes/CERATOPHYLLUS_STYX');
var CHABERTIA_OVINA = require('./routes/CHABERTIA_OVINA');
var CHAETODACTYLUS_KROMBEINI = require('./routes/CHAETODACTYLUS_KROMBEINI');
var CHAETODACTYLUS_MICHENERI = require('./routes/CHAETODACTYLUS_MICHENERI');
var CHAETODACTYLUS_SP = require('./routes/CHAETODACTYLUS_SP');
var CHEILOSPIRURA_HAMULOSA = require('./routes/CHEILOSPIRURA_HAMULOSA');
var CICHLASOTREMA_UJATI = require('./routes/CICHLASOTREMA_UJATI');
var CITELLINEMA_BIFURCATUM = require('./routes/CITELLINEMA_BIFURCATUM');
var CITTOTAENIA_VARIABILIS = require('./routes/CITTOTAENIA_VARIABILIS');
var CLARKUS_PAPILLATUS = require('./routes/CLARKUS_PAPILLATUS');
var CLINOSTOMUM_COMPLANATUM = require('./routes/CLINOSTOMUM_COMPLANATUM');
var CLONORCHIS_SINENSIS = require('./routes/CLONORCHIS_SINENSIS');
var CONTRACAECUM_MULTIPAPILLATUM = require('./routes/CONTRACAECUM_MULTIPAPILLATUM');
var CONTRACAECUM_SPICULIGERUM = require('./routes/CONTRACAECUM_SPICULIGERUM');
var COOPERIA_CURTICEI = require('./routes/COOPERIA_CURTICEI');
var COOPERIA_ONCOPHORA = require('./routes/COOPERIA_ONCOPHORA');
var COOPERIA_PUNCTATA = require('./routes/COOPERIA_PUNCTATA');
var COOPERIA_SURNABADA = require('./routes/COOPERIA_SURNABADA');
var CORACIACARUS_CUCULI = require('./routes/CORACIACARUS_CUCULI');




var HORSTIA_SP = require('./routes/HORSTIA_SP');
var HYALOMMA_AEGYPTIUM = require('./routes/HYALOMMA_AEGYPTIUM');
var HYALOMMA_ALBIPARMATUM = require('./routes/HYALOMMA_ALBIPARMATUM');
var HYALOMMA_ANATOLICUM = require('./routes/HYALOMMA_ANATOLICUM');
var HYALOMMA_DROMEDARII = require('./routes/HYALOMMA_DROMEDARII');
var HYALOMMA_IMPELTATUM = require('./routes/HYALOMMA_IMPELTATUM');
var HYALOMMA_IMPRESSUM = require('./routes/HYALOMMA_IMPRESSUM');
var HYALOMMA_RUFIPES = require('./routes/HYALOMMA_RUFIPES');
var HYALOMMA_TRUNCATUM = require('./routes/HYALOMMA_TRUNCATUM');
var HYALOMMA_TURANICUM = require('./routes/HYALOMMA_TURANICUM');
var HYMENOLEPIS_DIMINUTA = require('./routes/HYMENOLEPIS_DIMINUTA');
var HYPOPI_SP = require('./routes/HYPOPI_SP');
var HYSTRICHOPSYLLA_ORIENTALIS = require('./routes/HYSTRICHOPSYLLA_ORIENTALIS');
var HYSTRICHOPSYLLA_TALPAE = require('./routes/HYSTRICHOPSYLLA_TALPAE');
var IRONUS_IGNAVUS = require('./routes/IRONUS_IGNAVUS');
var ISCHNOPSYLLUS_HEXACTENUS = require('./routes/ISCHNOPSYLLUS_HEXACTENUS');
var ISCHNOPSYLLUS_INTERMEDIUS = require('./routes/ISCHNOPSYLLUS_INTERMEDIUS');
var ISCHNOPSYLLUS_OCTACTENUS = require('./routes/ISCHNOPSYLLUS_OCTACTENUS');
var IXODES_ANGUSTUS = require('./routes/IXODES_ANGUSTUS');
var IXODES_ARAGAOI = require('./routes/IXODES_ARAGAOI');
var IXODES_ARBORICOLA = require('./routes/IXODES_ARBORICOLA');
var IXODES_CAVIPALPUS = require('./routes/IXODES_CAVIPALPUS');
var IXODES_COOKEI = require('./routes/IXODES_COOKEI');
var IXODES_CUMULATIMPUNCTATUS = require('./routes/IXODES_CUMULATIMPUNCTATUS');
var IXODES_FRONTALIS = require('./routes/IXODES_FRONTALIS');
var IXODES_HEXAGONUS = require('./routes/IXODES_HEXAGONUS');
var IXODES_HOLOCYCLUS = require('./routes/IXODES_HOLOCYCLUS');
var IXODES_KINGI = require('./routes/IXODES_KINGI');
var IXODES_LEWISI = require('./routes/IXODES_LEWISI');
var IXODES_LIVIDUS = require('./routes/IXODES_LIVIDUS');
var IXODES_MUNIENSIS = require('./routes/IXODES_MUNIENSIS');
var IXODES_PACIFICUS = require('./routes/IXODES_PACIFICUS');
var IXODES_PILOSUS = require('./routes/IXODES_PILOSUS');
var IXODES_RASUS = require('./routes/IXODES_RASUS');
var IXODES_RUBICUNDUS = require('./routes/IXODES_RUBICUNDUS');
var IXODES_SCAPULARIS = require('./routes/IXODES_SCAPULARIS');
var IXODES_SCULPTUS = require('./routes/IXODES_SCULPTUS');
var IXODES_SIMPLEX = require('./routes/IXODES_SIMPLEX');
var IXODES_SPINIPALPIS = require('./routes/IXODES_SPINIPALPIS');
var IXODES_TRIANGULICEPS = require('./routes/IXODES_TRIANGULICEPS');
var JELLISONIA_BONIA = require('./routes/JELLISONIA_BONIA');
var JELLISONIA_GRAYI = require('./routes/JELLISONIA_GRAYI');
var JELLISONIA_HAYESI = require('./routes/JELLISONIA_HAYESI');
var JELLISONIA_KLOTSI = require('./routes/JELLISONIA_KLOTSI');
var JELLISONIA_WISEMANI = require('./routes/JELLISONIA_WISEMANI');
var KALICEPHALUS_COSTATUS_INDICUS = require('./routes/KALICEPHALUS_COSTATUS_INDICUS');
var KALICEPHALUS_VIPERAE_CHUNGKINGENSIS = require('./routes/KALICEPHALUS_VIPERAE_CHUNGKINGENSIS');
var KOHLSIA_PELAEZI = require('./routes/KOHLSIA_PELAEZI');
var LABIOSTOMUM_RAUSCHI = require('./routes/LABIOSTOMUM_RAUSCHI');
var LEPTOLAIMUS_PUCCINELLIAE = require('./routes/LEPTOLAIMUS_PUCCINELLIAE');
var LEPTOPSYLLA_SEGNIS = require('./routes/LEPTOPSYLLA_SEGNIS');
var LEPTOPSYLLA_TASCHENBERGI = require('./routes/LEPTOPSYLLA_TASCHENBERGI');
var LEPTORHYNCHOIDES_THECATUS = require('./routes/LEPTORHYNCHOIDES_THECATUS');
var LIGULA_INTESTINALIS = require('./routes/LIGULA_INTESTINALIS');
var MACRACANTHORHYNCHUS_INGENS = require('./routes/MACRACANTHORHYNCHUS_INGENS');
var MACROPOSTHONIA_ORNATA = require('./routes/MACROPOSTHONIA_ORNATA');
var MARGAROPUS_WINTHEMI = require('./routes/MARGAROPUS_WINTHEMI');
var MARSHALLAGIA_MARSHALLI = require('./routes/MARSHALLAGIA_MARSHALLI');
var MAZAMASTRONGYLUS_ODOCOILEI = require('./routes/MAZAMASTRONGYLUS_ODOCOILEI');


var NEMATODIRUS_ABNORMALIS = require('./routes/NEMATODIRUS_ABNORMALIS');


var PALAEOPSYLLA_KOHAUTI = require('./routes/PALAEOPSYLLA_KOHAUTI');


var PLECTUS_CIRRATUS = require('./routes/PLECTUS_CIRRATUS');


var RAILLIETINA_SKRJABINIA_CESTICILLUS = require('./routes/RAILLIETINA_SKRJABINIA_CESTICILLUS');

// (Sept 10) Gio starting at Rhi. longus

// Add species above here and then scroll down
// to add page reference (step 1 of 2)
/*******************************************/

var about = require('./routes/about');
var team = require('./routes/team');
var atlas = require('./routes/atlas');

var app = express();
//var routes = require('./routes/index');

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

// uncomment after placing Nova favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: false
}));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

// Enhanced error checking (GLOBAL)
var isType = function(obj) {
    return ({}).toString.call(obj).match(/\s([a-zA-Z]+)/)[1].toLowerCase();
};
module.exports = isType;

app.use('/', routes);

/* Tell middleware to send out species pages...*/
app.use('/ABBREVIATA_BANCROFTI', ABBREVIATA_BANCROFTI);
app.use('/ABBREVIATA_HASTASPICULA', ABBREVIATA_HASTASPICULA);
app.use('/AGLENCHUS_AGRICOLA', AGLENCHUS_AGRICOLA);
app.use('/ALAIMUS_PRIMITIVUS', ALAIMUS_PRIMITIVUS);
app.use('/ALLOCORRIGIA_FILIFORMIS', ALLOCORRIGIA_FILIFORMIS);
app.use('/ALLOGLOSSIDIUM_CORTI', ALLOGLOSSIDIUM_CORTI);
app.use('/AMALARAEUS_PENICILLIGER', AMALARAEUS_PENICILLIGER);
app.use('/AMBLYOMMA_AMERICANUM', AMBLYOMMA_AMERICANUM);
app.use('/AMBLYOMMA_ASTRION', AMBLYOMMA_ASTRION);
app.use('/AMBLYOMMA_CAJENNENSE', AMBLYOMMA_CAJENNENSE);
app.use('/AMBLYOMMA_COHAERENS', AMBLYOMMA_COHAERENS);
app.use('/AMBLYOMMA_COMPRESSUM', AMBLYOMMA_COMPRESSUM);
app.use('/AMBLYOMMA_CUNEATUM', AMBLYOMMA_CUNEATUM);
app.use('/AMBLYOMMA_EBERNEUM', AMBLYOMMA_EBERNEUM);
app.use('/AMBLYOMMA_EXORNATUM', AMBLYOMMA_EXORNATUM);
app.use('/AMBLYOMMA_FALSOMARMOREUM', AMBLYOMMA_FALSOMARMOREUM);
app.use('/AMBLYOMMA_FIMBRIATUM', AMBLYOMMA_FIMBRIATUM);
app.use('/AMBLYOMMA_FLAVOMACULATUM', AMBLYOMMA_FLAVOMACULATUM);
app.use('/AMBLYOMMA_GEMMA', AMBLYOMMA_GEMMA);
app.use('/AMBLYOMMA_GEOEMYDAE', AMBLYOMMA_GEOEMYDAE);
app.use('/AMBLYOMMA_HEBRAEUM', AMBLYOMMA_HEBRAEUM);
app.use('/AMBLYOMMA_HELVOLUM', AMBLYOMMA_HELVOLUM);
app.use('/AMBLYOMMA_JAVANENSE', AMBLYOMMA_JAVANENSE);
app.use('/AMBLYOMMA_LATUM', AMBLYOMMA_LATUM);
app.use('/AMBLYOMMA_LEPIDUM', AMBLYOMMA_LEPIDUM);
app.use('/AMBLYOMMA_LIMBATUM', AMBLYOMMA_LIMBATUM);
app.use('/AMBLYOMMA_MACULATUM', AMBLYOMMA_MACULATUM);
app.use('/AMBLYOMMA_MARMOREUM', AMBLYOMMA_MARMOREUM);
app.use('/AMBLYOMMA_NUTTALLI', AMBLYOMMA_NUTTALLI);
app.use('/AMBLYOMMA_PAULOPUNCTATUM', AMBLYOMMA_PAULOPUNCTATUM);
app.use('/AMBLYOMMA_POMPOSUM', AMBLYOMMA_POMPOSUM);
app.use('/AMBLYOMMA_RHINOCEROTIS', AMBLYOMMA_RHINOCEROTIS);
app.use('/AMBLYOMMA_SPARSUM', AMBLYOMMA_SPARSUM);
app.use('/AMBLYOMMA_SPLENDIDUM', AMBLYOMMA_SPLENDIDUM);
app.use('/AMBLYOMMA_TESTUDINARIUM', AMBLYOMMA_TESTUDINARIUM);
app.use('/AMBLYOMMA_THOLLONI', AMBLYOMMA_THOLLONI);
app.use('/AMBLYOMMA_TRIGUTTATUM', AMBLYOMMA_TRIGUTTATUM);
app.use('/AMBLYOMMA_VARIEGATUM', AMBLYOMMA_VARIEGATUM);
app.use('/ANAPLECTUS_GRANULOSUS', ANAPLECTUS_GRANULOSUS);
app.use('/ANCYLOSTOMA_CANINUM', ANCYLOSTOMA_CANINUM);
app.use('/ANGIOSTRONGYLUS_CANTONENSIS', ANGIOSTRONGYLUS_CANTONENSIS);
app.use('/ANOMIOPSYLLUS_NUDATUS', ANOMIOPSYLLUS_NUDATUS);
app.use('/ANOPLOCEPHALA_PERFOLIATA', ANOPLOCEPHALA_PERFOLIATA);
app.use('/APHELENCHUS_AVENAE', APHELENCHUS_AVENAE);
app.use('/APHELENCHUS_PARIETINUS', APHELENCHUS_PARIETINUS);
app.use('/APLECTANA_ITZOCANENSIS', APLECTANA_ITZOCANENSIS);
app.use('/APORCELAIMELLUS_OBTUSICAUDATUS', APORCELAIMELLUS_OBTUSICAUDATUS);
app.use('/ARALICHUS_NOBILIS', ARALICHUS_NOBILIS);
app.use('/ARCHAEOPSYLLA_ERINACEI', ARCHAEOPSYLLA_ERINACEI);
app.use('/ARGAS_BRUMPTI', ARGAS_BRUMPTI);
app.use('/ARGAS_CONFUSUS', ARGAS_CONFUSUS);
app.use('/ARGAS_PERSICUS', ARGAS_PERSICUS);
app.use('/ARGAS_VESPERTILIONIS', ARGAS_VESPERTILIONIS);
app.use('/ARGAS_WALKERAE', ARGAS_WALKERAE);
app.use('/ARHYTHMORHYNCHUS_BREVIS', ARHYTHMORHYNCHUS_BREVIS);
app.use('/ASCARIDIA_BONASAE', ASCARIDIA_BONASAE);
app.use('/ASCARIDIA_COLUMBAE', ASCARIDIA_COLUMBAE);
app.use('/ASCARIDIA_GALLI', ASCARIDIA_GALLI);
app.use('/ASCARIDIA_LINEATA', ASCARIDIA_LINEATA);
app.use('/ASCARIS_LUMBRICOIDES', ASCARIS_LUMBRICOIDES);
app.use('/ASCARIS_SUUM', ASCARIS_SUUM);
app.use('/ASCOCOTYLE_LONGA', ASCOCOTYLE_LONGA);
app.use('/ASCOCOTYLE_TENUICOLLIS', ASCOCOTYLE_TENUICOLLIS);
app.use('/BAYLISASCARIS_PROCYONIS', BAYLISASCARIS_PROCYONIS);
app.use('/BOTHRIOCEPHALUS_CUSPIDATUS', BOTHRIOCEPHALUS_CUSPIDATUS);
app.use('/BOTHRIOCROTON_HYDROSAURI', BOTHRIOCROTON_HYDROSAURI);
app.use('/BRACHYCOELIUM_SALAMANDRAE', BRACHYCOELIUM_SALAMANDRAE);
app.use('/BUNOSTOMUM_PHLEBOTOMUM', BUNOSTOMUM_PHLEBOTOMUM);
app.use('/BUNOSTOMUM_TRIGONOCEPHALUM', BUNOSTOMUM_TRIGONOCEPHALUM);
app.use('/CAMALLANUS_OXYCEPHALUS', CAMALLANUS_OXYCEPHALUS);
app.use('/CAPILLARIA_CONTORTA', CAPILLARIA_CONTORTA);
app.use('/CAPILLARIA_TENUISSIMA', CAPILLARIA_TENUISSIMA);
app.use('/CARIOS_VESPERTILIONIS', CARIOS_VESPERTILIONIS);
app.use('/CENTROCESTUS_FORMOSANUS', CENTROCESTUS_FORMOSANUS);
app.use('/CEPHALURIS_COLORADENSIS', CEPHALURIS_COLORADENSIS);
app.use('/CERATOPHYLLUS_FARRENI', CERATOPHYLLUS_FARRENI);
app.use('/CERATOPHYLLUS_GALLINAE', CERATOPHYLLUS_GALLINAE);
app.use('/CERATOPHYLLUS_GAREI', CERATOPHYLLUS_GAREI);
app.use('/CERATOPHYLLUS_HIRUNDINIS', CERATOPHYLLUS_HIRUNDINIS);
app.use('/CERATOPHYLLUS_STYX', CERATOPHYLLUS_STYX);
app.use('/CHABERTIA_OVINA', CHABERTIA_OVINA);
app.use('/CHAETODACTYLUS_KROMBEINI', CHAETODACTYLUS_KROMBEINI);
app.use('/CHAETODACTYLUS_MICHENERI', CHAETODACTYLUS_MICHENERI);
app.use('/CHAETODACTYLUS_SP', CHAETODACTYLUS_SP);
app.use('/CHEILOSPIRURA_HAMULOSA', CHEILOSPIRURA_HAMULOSA);
app.use('/CICHLASOTREMA_UJATI', CICHLASOTREMA_UJATI);
app.use('/CITELLINEMA_BIFURCATUM', CITELLINEMA_BIFURCATUM);
app.use('/CITTOTAENIA_VARIABILIS', CITTOTAENIA_VARIABILIS);
app.use('/CLARKUS_PAPILLATUS', CLARKUS_PAPILLATUS);
app.use('/CLINOSTOMUM_COMPLANATUM', CLINOSTOMUM_COMPLANATUM);
app.use('/CLONORCHIS_SINENSIS', CLONORCHIS_SINENSIS);
app.use('/CONTRACAECUM_MULTIPAPILLATUM', CONTRACAECUM_MULTIPAPILLATUM);
app.use('/CONTRACAECUM_SPICULIGERUM', CONTRACAECUM_SPICULIGERUM);
app.use('/COOPERIA_CURTICEI', COOPERIA_CURTICEI);
app.use('/COOPERIA_ONCOPHORA', COOPERIA_ONCOPHORA);
app.use('/COOPERIA_PUNCTATA', COOPERIA_PUNCTATA);
app.use('/COOPERIA_SURNABADA', COOPERIA_SURNABADA);
app.use('/CORACIACARUS_CUCULI', CORACIACARUS_CUCULI);


app.use('/HORSTIA_SP', HORSTIA_SP);
app.use('/HYALOMMA_AEGYPTIUM', HYALOMMA_AEGYPTIUM);
app.use('/HYALOMMA_ALBIPARMATUM', HYALOMMA_ALBIPARMATUM);
app.use('/HYALOMMA_ANATOLICUM', HYALOMMA_ANATOLICUM);
app.use('/HYALOMMA_DROMEDARII', HYALOMMA_DROMEDARII);
app.use('/HYALOMMA_IMPELTATUM', HYALOMMA_IMPELTATUM);
app.use('/HYALOMMA_IMPRESSUM', HYALOMMA_IMPRESSUM);
app.use('/HYALOMMA_RUFIPES', HYALOMMA_RUFIPES);
app.use('/HYALOMMA_TRUNCATUM', HYALOMMA_TRUNCATUM);
app.use('/HYALOMMA_TURANICUM', HYALOMMA_TURANICUM);
app.use('/HYMENOLEPIS_DIMINUTA', HYMENOLEPIS_DIMINUTA);
app.use('/HYPOPI_SP', HYPOPI_SP);
app.use('/HYSTRICHOPSYLLA_ORIENTALIS', HYSTRICHOPSYLLA_ORIENTALIS);
app.use('/HYSTRICHOPSYLLA_TALPAE', HYSTRICHOPSYLLA_TALPAE);
app.use('/IRONUS_IGNAVUS', IRONUS_IGNAVUS);
app.use('/ISCHNOPSYLLUS_HEXACTENUS', ISCHNOPSYLLUS_HEXACTENUS);
app.use('/ISCHNOPSYLLUS_INTERMEDIUS', ISCHNOPSYLLUS_INTERMEDIUS);
app.use('/ISCHNOPSYLLUS_OCTACTENUS', ISCHNOPSYLLUS_OCTACTENUS);
app.use('/IXODES_ANGUSTUS', IXODES_ANGUSTUS);
app.use('/IXODES_ARAGAOI', IXODES_ARAGAOI);
app.use('/IXODES_ARBORICOLA', IXODES_ARBORICOLA);
app.use('/IXODES_CAVIPALPUS', IXODES_CAVIPALPUS);
app.use('/IXODES_COOKEI', IXODES_COOKEI);
app.use('/IXODES_CUMULATIMPUNCTATUS', IXODES_CUMULATIMPUNCTATUS);
app.use('/IXODES_FRONTALIS', IXODES_FRONTALIS);
app.use('/IXODES_HEXAGONUS', IXODES_HEXAGONUS);
app.use('/IXODES_HOLOCYCLUS', IXODES_HOLOCYCLUS);
app.use('/IXODES_KINGI', IXODES_KINGI);
app.use('/IXODES_LEWISI', IXODES_LEWISI);
app.use('/IXODES_LIVIDUS', IXODES_LIVIDUS);
app.use('/IXODES_MUNIENSIS', IXODES_MUNIENSIS);
app.use('/IXODES_PACIFICUS', IXODES_PACIFICUS);
app.use('/IXODES_PILOSUS', IXODES_PILOSUS);
app.use('/IXODES_RASUS', IXODES_RASUS);
app.use('/IXODES_RUBICUNDUS', IXODES_RUBICUNDUS);
app.use('/IXODES_SCAPULARIS', IXODES_SCAPULARIS);
app.use('/IXODES_SCULPTUS', IXODES_SCULPTUS);
app.use('/IXODES_SIMPLEX', IXODES_SIMPLEX);
app.use('/IXODES_SPINIPALPIS', IXODES_SPINIPALPIS);
app.use('/IXODES_TRIANGULICEPS', IXODES_TRIANGULICEPS);
app.use('/JELLISONIA_BONIA', JELLISONIA_BONIA);
app.use('/JELLISONIA_GRAYI', JELLISONIA_GRAYI);
app.use('/JELLISONIA_HAYESI', JELLISONIA_HAYESI);
app.use('/JELLISONIA_KLOTSI', JELLISONIA_KLOTSI);
app.use('/JELLISONIA_WISEMANI', JELLISONIA_WISEMANI);
app.use('/KALICEPHALUS_COSTATUS_INDICUS', KALICEPHALUS_COSTATUS_INDICUS);
app.use('/KALICEPHALUS_VIPERAE_CHUNGKINGENSIS', KALICEPHALUS_VIPERAE_CHUNGKINGENSIS);
app.use('/KOHLSIA_PELAEZI', KOHLSIA_PELAEZI);
app.use('/LABIOSTOMUM_RAUSCHI', LABIOSTOMUM_RAUSCHI);
app.use('/LEPTOLAIMUS_PUCCINELLIAE', LEPTOLAIMUS_PUCCINELLIAE);
app.use('/LEPTOPSYLLA_SEGNIS', LEPTOPSYLLA_SEGNIS);
app.use('/LEPTOPSYLLA_TASCHENBERGI', LEPTOPSYLLA_TASCHENBERGI);
app.use('/LEPTORHYNCHOIDES_THECATUS', LEPTORHYNCHOIDES_THECATUS);
app.use('/LIGULA_INTESTINALIS', LIGULA_INTESTINALIS);
app.use('/MACRACANTHORHYNCHUS_INGENS', MACRACANTHORHYNCHUS_INGENS);
app.use('/MACROPOSTHONIA_ORNATA', MACROPOSTHONIA_ORNATA);
app.use('/MARGAROPUS_WINTHEMI', MARGAROPUS_WINTHEMI);
app.use('/MARSHALLAGIA_MARSHALLI', MARSHALLAGIA_MARSHALLI);
app.use('/MAZAMASTRONGYLUS_ODOCOILEI', MAZAMASTRONGYLUS_ODOCOILEI);


app.use('/NEMATODIRUS_ABNORMALIS', NEMATODIRUS_ABNORMALIS);


app.use('/PALAEOPSYLLA_KOHAUTI', PALAEOPSYLLA_KOHAUTI);


app.use('/PLECTUS_CIRRATUS', PLECTUS_CIRRATUS);


app.use('/RAILLIETINA_SKRJABINIA_CESTICILLUS', RAILLIETINA_SKRJABINIA_CESTICILLUS);

// Add page reference here (step 2)
/*******************************************/

app.use('/about', about);
app.use('/team', team);
app.use('/atlas', atlas);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: err
        });
    });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});

module.exports = app;
